// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi.Models
{
    public partial class ActivityDetail
    {
        public ActivityDetail()
        {
            ActivityCoupons = new HashSet<ActivityCoupon>();
            ActivityDiscounts = new HashSet<ActivityDiscount>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int ActivityId { get; set; }
        public string Description { get; set; }
        public string Thumbnail { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
        public string Status { get; set; }
        public DateTime CreatedAt { get; set; }

        public virtual Activity Activity { get; set; }
        public virtual ICollection<ActivityCoupon> ActivityCoupons { get; set; }
        public virtual ICollection<ActivityDiscount> ActivityDiscounts { get; set; }
    }
}