// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi.Models
{
    public partial class ActivityDiscount
    {
        public ActivityDiscount()
        {
            MemberLevels = new HashSet<MemberLevel>();
            MemberTags = new HashSet<MemberTag>();
            ProductTags = new HashSet<ProductTag>();
            ThirdCategories = new HashSet<ThirdCategory>();
        }

        public int Id { get; set; }
        public int AcitivityDetailId { get; set; }
        public int TargetTypeId { get; set; }
        public int PromotionProductTypeId { get; set; }
        public int PriceThreshold { get; set; }
        public int DiscountTypeId { get; set; }
        public int? DiscountQty { get; set; }
        public decimal? Amount { get; set; }
        public int? FreebieId { get; set; }
        public int? GiftCouponId { get; set; }
        public bool ExtraSalesUsage { get; set; }

        public virtual ActivityDetail AcitivityDetail { get; set; }
        public virtual DiscountType DiscountType { get; set; }
        public virtual Freeby Freebie { get; set; }
        public virtual Coupon GiftCoupon { get; set; }
        public virtual PromotionProductType PromotionProductType { get; set; }
        public virtual TargetType TargetType { get; set; }

        public virtual ICollection<MemberLevel> MemberLevels { get; set; }
        public virtual ICollection<MemberTag> MemberTags { get; set; }
        public virtual ICollection<ProductTag> ProductTags { get; set; }
        public virtual ICollection<ThirdCategory> ThirdCategories { get; set; }
    }
}