// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi.Models
{
    public partial class CartDetail
    {
        public CartDetail()
        {
            CartHistories = new HashSet<CartHistory>();
        }

        public int Id { get; set; }
        public int CartsId { get; set; }
        public int ProductStylesId { get; set; }
        public int Quantity { get; set; }

        public virtual Cart Carts { get; set; }
        public virtual ProductStyle ProductStyles { get; set; }
        public virtual ICollection<CartHistory> CartHistories { get; set; }
    }
}