// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi.Models
{
    public partial class Coach
    {
        public Coach()
        {
            ExperienceEnrollments = new HashSet<ExperienceEnrollment>();
            Skillcurricula = new HashSet<Skillcurriculum>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string Img { get; set; }
        public bool? Status { get; set; }

        public virtual ICollection<ExperienceEnrollment> ExperienceEnrollments { get; set; }
        public virtual ICollection<Skillcurriculum> Skillcurricula { get; set; }
    }
}