// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi.Models
{
    public partial class Conversation
    {
        public Guid Id { get; set; }
        public string Message { get; set; }
        public int MemberId { get; set; }
        public DateTime SendTime { get; set; }
        public bool IsSelf { get; set; }

        public virtual Member Member { get; set; }
    }
}