// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi.Models
{
    public partial class Coupon
    {
        public Coupon()
        {
            ActivityCoupons = new HashSet<ActivityCoupon>();
            ActivityDiscounts = new HashSet<ActivityDiscount>();
            CouponSendＭembers = new HashSet<CouponSendＭember>();
            OrderUsedCoupons = new HashSet<OrderUsedCoupon>();
            MemberLevels = new HashSet<MemberLevel>();
            MemberTags = new HashSet<MemberTag>();
            ProductTags = new HashSet<ProductTag>();
            ThirdCategories = new HashSet<ThirdCategory>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public int EventTypeId { get; set; }
        public DateTime? PrevTime { get; set; }
        public DateTime? StartTime { get; set; }
        public DateTime? EndTime { get; set; }
        public string RepeatRule { get; set; }
        public byte? RepeatNum { get; set; }
        public int TargetTypeId { get; set; }
        public int? PromotionProductTypeId { get; set; }
        public string Status { get; set; }
        public int PriceThreshold { get; set; }
        public int CouponTypeId { get; set; }
        public int? DiscountQty { get; set; }
        public decimal? Amount { get; set; }
        public int? FreebieId { get; set; }
        public int? Quantity { get; set; }
        public bool ExtraSalesUsage { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime LastModified { get; set; }

        public virtual CouponType CouponType { get; set; }
        public virtual EventType EventType { get; set; }
        public virtual Freeby Freebie { get; set; }
        public virtual PromotionProductType PromotionProductType { get; set; }
        public virtual TargetType TargetType { get; set; }
        public virtual ICollection<ActivityCoupon> ActivityCoupons { get; set; }
        public virtual ICollection<ActivityDiscount> ActivityDiscounts { get; set; }
        public virtual ICollection<CouponSendＭember> CouponSendＭembers { get; set; }
        public virtual ICollection<OrderUsedCoupon> OrderUsedCoupons { get; set; }

        public virtual ICollection<MemberLevel> MemberLevels { get; set; }
        public virtual ICollection<MemberTag> MemberTags { get; set; }
        public virtual ICollection<ProductTag> ProductTags { get; set; }
        public virtual ICollection<ThirdCategory> ThirdCategories { get; set; }
    }
}