// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi.Models
{
    public partial class FirstCategory
    {
        public FirstCategory()
        {
            SecondCategories = new HashSet<SecondCategory>();
        }

        public int Id { get; set; }
        public string Name { get; set; }

        public virtual ICollection<SecondCategory> SecondCategories { get; set; }
    }
}