// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi.Models
{
    public partial class MemberLevelDetail
    {
        public int Id { get; set; }
        public int MemberId { get; set; }
        public int MemberLevelId { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }

        public virtual Member Member { get; set; }
        public virtual MemberLevel MemberLevel { get; set; }
    }
}