// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi.Models
{
    public partial class MemberLevel
    {
        public MemberLevel()
        {
            MemberLevelDetails = new HashSet<MemberLevelDetail>();
            MemberLevelDetails_Histories = new HashSet<MemberLevelDetails_History>();
            Members = new HashSet<Member>();
            ActivityDiscounts = new HashSet<ActivityDiscount>();
            Coupons = new HashSet<Coupon>();
        }

        public int Id { get; set; }
        public int LevelOrder { get; set; }
        public string Name { get; set; }
        public int UpgradePrice { get; set; }
        public int UpgradeOrderCount { get; set; }
        public int TimePeriod { get; set; }
        public decimal GainPointRate { get; set; }
        public string Description { get; set; }
        public string LevelName { get; set; }

        public virtual ICollection<MemberLevelDetail> MemberLevelDetails { get; set; }
        public virtual ICollection<MemberLevelDetails_History> MemberLevelDetails_Histories { get; set; }
        public virtual ICollection<Member> Members { get; set; }

        public virtual ICollection<ActivityDiscount> ActivityDiscounts { get; set; }
        public virtual ICollection<Coupon> Coupons { get; set; }
    }
}