// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi.Models
{
    public partial class MemberPoint
    {
        public int Id { get; set; }
        public int MemberId { get; set; }
        public int OrderId { get; set; }
        public int PointStatusId { get; set; }
        public int GainPoints { get; set; }

        public virtual Member Member { get; set; }
        public virtual Order Order { get; set; }
        public virtual PointStatus PointStatus { get; set; }
    }
}