// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi.Models
{
    public partial class MemberTag
    {
        public MemberTag()
        {
            MemberTagConditions = new HashSet<MemberTagCondition>();
            ActivityDiscounts = new HashSet<ActivityDiscount>();
            Coupons = new HashSet<Coupon>();
            Members = new HashSet<Member>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime CreateAt { get; set; }
        public string Description { get; set; }

        public virtual ICollection<MemberTagCondition> MemberTagConditions { get; set; }

        public virtual ICollection<ActivityDiscount> ActivityDiscounts { get; set; }
        public virtual ICollection<Coupon> Coupons { get; set; }
        public virtual ICollection<Member> Members { get; set; }
    }
}