// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi.Models
{
    public partial class MemberTagCondition
    {
        public int Id { get; set; }
        public int MemberTagId { get; set; }
        public string Name { get; set; }
        public string Operator { get; set; }
        public decimal Value { get; set; }
        public string Unit { get; set; }

        public virtual MemberTag MemberTag { get; set; }
    }
}