// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi.Models
{
    public partial class Order
    {
        public Order()
        {
            MemberPoints = new HashSet<MemberPoint>();
            OrderDetails = new HashSet<OrderDetail>();
            OrderReturnDetails = new HashSet<OrderReturnDetail>();
            OrderUsedCoupons = new HashSet<OrderUsedCoupon>();
            Payments = new HashSet<Payment>();
            ProductComments = new HashSet<ProductComment>();
        }

        public int Id { get; set; }
        public int MemberId { get; set; }
        public string Snapshot { get; set; }
        public string RecipientName { get; set; }
        public string RecipientPhone { get; set; }
        public string RecipientAddress { get; set; }
        public int OrderStatusId { get; set; }
        public DateTime CreateAt { get; set; }
        public string Note { get; set; }
        public int TotalProductsPrice { get; set; }
        public int DeliverPrice { get; set; }
        public int DiscountPrice { get; set; }
        public int UsedPoint { get; set; }
        public string RecipientEmail { get; set; }

        public virtual Member Member { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual ICollection<MemberPoint> MemberPoints { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<OrderReturnDetail> OrderReturnDetails { get; set; }
        public virtual ICollection<OrderUsedCoupon> OrderUsedCoupons { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
        public virtual ICollection<ProductComment> ProductComments { get; set; }
    }
}