// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi.Models
{
    public partial class Payment
    {
        public int Id { get; set; }
        public int Amount { get; set; }
        public int? BumpOrderId { get; set; }
        public int? BumpSkillCourseEnrollmentId { get; set; }
        public string LineOrderId { get; set; }
        public string LineTransactionId { get; set; }
        public string ECPayMerchantTradeNo { get; set; }
        public string PayType { get; set; }
        public string Status { get; set; }

        public virtual Order BumpOrder { get; set; }
        public virtual SkillEnrollment BumpSkillCourseEnrollment { get; set; }
    }
}