// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi.Models
{
    public partial class SecondCategory
    {
        public SecondCategory()
        {
            ThirdCategories = new HashSet<ThirdCategory>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int FirstCategoryId { get; set; }

        public virtual FirstCategory FirstCategory { get; set; }
        public virtual ICollection<ThirdCategory> ThirdCategories { get; set; }
    }
}