// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi.Models
{
    public partial class SkillEnrollment
    {
        public SkillEnrollment()
        {
            Payments = new HashSet<Payment>();
        }

        public int Id { get; set; }
        public int SkillcurriculumsId { get; set; }
        public int MemberId { get; set; }
        public DateTime CreatedAt { get; set; }
        public int NumberOfPeople { get; set; }

        public virtual Member Member { get; set; }
        public virtual Skillcurriculum Skillcurriculums { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}