// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi.Models
{
    public partial class Skillcurriculum
    {
        public Skillcurriculum()
        {
            SkillEnrollments = new HashSet<SkillEnrollment>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public int FieldId { get; set; }
        public DateTime StartTime { get; set; }
        public DateTime EndTime { get; set; }
        public byte Week { get; set; }
        public DateTime StartDate { get; set; }
        public int SkillCoursesId { get; set; }
        public int CoachId { get; set; }
        public bool Status { get; set; }

        public virtual Coach Coach { get; set; }
        public virtual Field Field { get; set; }
        public virtual SkillCourse SkillCourses { get; set; }
        public virtual ICollection<SkillEnrollment> SkillEnrollments { get; set; }
    }
}