// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace webapi.Models
{
    public partial class TrendingQuestion
    {
        public int Id { get; set; }
        public int QuestionTypeId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }

        public virtual TrendingQuestionType QuestionType { get; set; }
    }
}